"""Schema contracts for Trinity runtime artifacts."""

from .candidate import (
    CandidateLineage,
    CandidateRecord,
    CandidateScores,
    CandidateState,
    CandidateType,
    ReworkRoute,
)
from .evidence import (
    EvidenceFreshnessWindow,
    EvidenceProvenance,
    EvidenceSourceRef,
    EvidenceSourceType,
    EvidenceUnit,
)
from .integration import (
    REPLY_CONTRACT_VERSION,
    AcceptedArtifactVersion,
    CandidateDraft,
    DraftOutcomeDisposition,
    DraftOutcomeEvent,
    GoldenExample,
    RankedDraftSet,
    ReplyDraftCandidate,
    ReplyEvidenceEnvelope,
    ReplyFeedbackDisposition,
    ReplyFeedbackEvent,
    RuntimeTraceExport,
    ThreadContextSnippet,
    ThreadMessageRole,
    ThreadMessageSnapshot,
    ThreadSnapshot,
)

__all__ = [
    "CandidateLineage",
    "CandidateDraft",
    "CandidateRecord",
    "CandidateScores",
    "CandidateState",
    "CandidateType",
    "DraftOutcomeDisposition",
    "DraftOutcomeEvent",
    "EvidenceFreshnessWindow",
    "EvidenceProvenance",
    "EvidenceSourceRef",
    "EvidenceSourceType",
    "EvidenceUnit",
    "GoldenExample",
    "REPLY_CONTRACT_VERSION",
    "RankedDraftSet",
    "ReworkRoute",
    "RuntimeTraceExport",
    "AcceptedArtifactVersion",
    "ReplyDraftCandidate",
    "ReplyEvidenceEnvelope",
    "ReplyFeedbackDisposition",
    "ReplyFeedbackEvent",
    "ThreadContextSnippet",
    "ThreadMessageRole",
    "ThreadMessageSnapshot",
    "ThreadSnapshot",
]
