"""Core runtime package for Trinity."""

from trinity_core.adapters import (
    REPLY_ADAPTER_NAME,
    SUPPORTED_ADAPTER_NAMES,
    TrinityAdapterDescriptor,
    normalize_adapter_name,
    require_supported_adapter,
)
from trinity_core.ops import RuntimeStoragePaths, resolve_runtime_storage_paths
from trinity_core.runtime import TrinityRuntime
from trinity_core.schemas import (
    CandidateLineage,
    CandidateRecord,
    CandidateScores,
    CandidateState,
    CandidateType,
    EvidenceFreshnessWindow,
    EvidenceProvenance,
    EvidenceSourceRef,
    EvidenceSourceType,
    EvidenceUnit,
    ReworkRoute,
)
from trinity_core.workflow import (
    CandidatePipelineResult,
    DuplicateEvidenceSuppressed,
    EvaluationDisposition,
    EvaluatorExecutionInput,
    EvidenceIngestionResult,
    GeneratorExecutionInput,
    InMemoryEvidenceStore,
    RawEvaluationResult,
    RawEvidenceInput,
    RawGeneratedCandidate,
    RawRefinerResult,
    RefinerDisposition,
    RefinerExecutionInput,
    StageExecutionResult,
    StageFailure,
    advance_candidate,
    canonicalize_content,
    compute_content_hash,
    create_candidate,
    execute_candidate_pipeline,
    fork_candidate_version,
    ingest_evidence,
    run_evaluator_stage,
    run_generator_stage,
    run_refiner_stage,
)

__all__ = [
    "advance_candidate",
    "CandidatePipelineResult",
    "CandidateLineage",
    "CandidateRecord",
    "CandidateScores",
    "CandidateState",
    "CandidateType",
    "create_candidate",
    "DuplicateEvidenceSuppressed",
    "EvaluationDisposition",
    "EvidenceFreshnessWindow",
    "EvidenceIngestionResult",
    "EvidenceProvenance",
    "EvidenceSourceRef",
    "EvidenceSourceType",
    "EvidenceUnit",
    "EvaluatorExecutionInput",
    "execute_candidate_pipeline",
    "fork_candidate_version",
    "GeneratorExecutionInput",
    "InMemoryEvidenceStore",
    "RawEvidenceInput",
    "RawEvaluationResult",
    "RawGeneratedCandidate",
    "RawRefinerResult",
    "REPLY_ADAPTER_NAME",
    "RefinerDisposition",
    "RefinerExecutionInput",
    "resolve_runtime_storage_paths",
    "SUPPORTED_ADAPTER_NAMES",
    "TrinityAdapterDescriptor",
    "TrinityRuntime",
    "ReworkRoute",
    "RuntimeStoragePaths",
    "StageExecutionResult",
    "StageFailure",
    "canonicalize_content",
    "compute_content_hash",
    "ingest_evidence",
    "normalize_adapter_name",
    "require_supported_adapter",
    "run_evaluator_stage",
    "run_generator_stage",
    "run_refiner_stage",
]
